apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  namespace: chat-prod
  labels:
    app: chat-app
    env: prod
spec:
  type: ClusterIP
  selector:
    app: chat-app
    env: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
